# Generated by Django 4.2.2 on 2023-06-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_institucion_externa', models.CharField(max_length=100)),
                ('codigo_senecyt', models.CharField(max_length=100)),
                ('codigo_toma_fisica', models.CharField(max_length=100)),
                ('codigo_anterior', models.CharField(max_length=100)),
                ('bien', models.CharField(max_length=50)),
                ('clase_bien', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('usuario_final', models.CharField(max_length=50)),
                ('nro_cedula', models.CharField(max_length=10)),
                ('ubicacion', models.CharField(max_length=100)),
                ('edificio', models.CharField(max_length=100)),
                ('custodio_administrativo', models.CharField(max_length=50)),
                ('delegado_1', models.CharField(max_length=50)),
                ('delegado_2', models.CharField(max_length=50)),
                ('delegado_3', models.CharField(max_length=50)),
                ('tipo_novedad', models.CharField(max_length=500)),
                ('observaciones', models.CharField(max_length=500)),
                ('nro_acta_entrega_recepcion', models.CharField(max_length=50)),
                ('nro_acta_donacion_factura', models.CharField(max_length=50)),
                ('valor_monetario', models.CharField(max_length=50)),
                ('fecha_entrega_recepcion', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
